'use strict';

const DEFAULT_CONFIG = {
  theme: 'dark', accentColor: '#38bdf8', settings: { cardWidth: 300, fontSize: 16, animations: true, backupCount: 10 }, categories: []
};

const $ = (id) => document.getElementById(id);
const uid = (prefix) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;

class Store {
  constructor() { this.key = 'admin-dashboard-config'; this.backupKey = 'admin-dashboard-backups'; this.data = structuredClone(DEFAULT_CONFIG); }
  async load() {
    const saved = localStorage.getItem(this.key);
    if (saved) { this.data = this.normalize(JSON.parse(saved)); return; }
    try { const response = await fetch('config.json', { cache: 'no-store' }); if (response.ok) this.data = this.normalize(await response.json()); }
    catch { this.data = structuredClone(DEFAULT_CONFIG); }
    this.save(false);
  }
  normalize(config) { return { ...structuredClone(DEFAULT_CONFIG), ...config, settings: { ...DEFAULT_CONFIG.settings, ...(config.settings || {}) }, categories: (config.categories || []).map((category, index) => ({ ...category, id: category.id || uid('cat'), order: category.order ?? index, collapsed: Boolean(category.collapsed), links: (category.links || []).map((link) => ({ favorite: false, openCount: 0, lastOpened: null, newTab: true, tags: [], ...link, id: link.id || uid('link') })) })) }; }
  save(withBackup = true) { localStorage.setItem(this.key, JSON.stringify(this.data)); if (withBackup) this.backup(); }
  backup() { const backups = JSON.parse(localStorage.getItem(this.backupKey) || '[]'); backups.unshift({ name: `config_${new Date().toISOString().replace(/[:T]/g, '-').slice(0, 19)}.json`, created: new Date().toISOString(), data: this.data }); localStorage.setItem(this.backupKey, JSON.stringify(backups.slice(0, this.data.settings.backupCount || 10))); }
  export(filename, content, type = 'application/json') { const blob = new Blob([content], { type }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
}

class Dashboard {
  constructor(store) { this.store = store; this.query = ''; this.editing = false; this.drag = null; this.elements = { dashboard: $('dashboard'), search: $('searchInput'), stats: $('stats'), dialog: $('itemDialog'), form: $('itemForm') }; }
  init() { this.bindGlobalActions(); this.applySettings(); this.render(); setInterval(() => this.renderClock(), 1000); this.renderClock(); }
  bindGlobalActions() {
    this.elements.search.addEventListener('input', (event) => { this.query = event.target.value.trim().toLowerCase(); this.render(); });
    this.elements.search.addEventListener('keydown', (event) => { if (event.key === 'Enter') this.openFirstResult(); if (event.key === 'Escape') { event.target.value = ''; this.query = ''; this.render(); } });
    $('editButton').addEventListener('click', () => { this.editing = !this.editing; document.body.classList.toggle('editing', this.editing); $('editButton').classList.toggle('active', this.editing); });
    $('themeButton').addEventListener('click', () => { this.store.data.theme = this.store.data.theme === 'dark' ? 'light' : 'dark'; this.store.save(); this.applySettings(); });
    $('favoritesButton').addEventListener('click', () => { this.query = 'favorite:true'; this.elements.search.value = this.query; this.render(); });
    $('exportButton').addEventListener('click', () => this.store.export('config.json', JSON.stringify(this.store.data, null, 2)));
    $('backupButton').addEventListener('click', () => { this.store.backup(); this.store.export(`config_${new Date().toISOString().slice(0,10)}.json`, JSON.stringify(this.store.data, null, 2)); });
    $('settingsButton').addEventListener('click', () => this.openCategoryDialog());
    $('addLinkButton').addEventListener('click', () => this.openLinkDialog(this.store.data.categories[0]?.id));
    $('importButton').addEventListener('click', () => $('fileImport').click());
    $('fileImport').addEventListener('change', (event) => this.importFile(event.target.files[0]));
    $('cancelDialog').addEventListener('click', () => this.elements.dialog.close());
    this.elements.form.addEventListener('submit', (event) => { event.preventDefault(); this.saveDialog(); });
    document.addEventListener('keydown', (event) => this.shortcuts(event));
  }
  shortcuts(event) { const key = event.key.toLowerCase(); if (event.ctrlKey && key === 'k') { event.preventDefault(); this.elements.search.focus(); } if (event.ctrlKey && key === 'n' && !event.shiftKey) { event.preventDefault(); this.openCategoryDialog(); } if (event.ctrlKey && event.shiftKey && key === 'n') { event.preventDefault(); this.openLinkDialog(this.store.data.categories[0]?.id); } if (event.ctrlKey && key === 's') { event.preventDefault(); $('exportButton').click(); } if (event.key === 'Escape' && this.elements.dialog.open) this.elements.dialog.close(); }
  applySettings() { document.body.classList.toggle('light', this.store.data.theme === 'light'); document.documentElement.style.setProperty('--accent', this.store.data.accentColor || '#38bdf8'); document.documentElement.style.setProperty('--card-width', `${this.store.data.settings.cardWidth}px`); document.documentElement.style.setProperty('--font-size', `${this.store.data.settings.fontSize}px`); }
  safeUrl(url) { try { const parsed = new URL(url); return ['http:', 'https:', 'file:'].includes(parsed.protocol); } catch { return false; } }
  matches(category, link) { if (!this.query) return true; if (this.query === 'favorite:true') return link.favorite; return [category.name, category.description, link.title, link.url, link.description, ...(link.tags || [])].join(' ').toLowerCase().includes(this.query); }
  render() { const fragment = document.createDocumentFragment(); const categories = [...this.store.data.categories].sort((a, b) => a.order - b.order); const favorites = this.favoriteCategory(); const visibleCategories = favorites.links.length ? [favorites, ...categories] : categories; let visibleLinks = 0; visibleCategories.forEach((category) => { const links = category.links.filter((link) => this.matches(category, link)); if (!links.length && this.query) return; visibleLinks += links.length; fragment.append(this.renderCategory(category, links)); }); this.elements.dashboard.replaceChildren(fragment); if (!this.elements.dashboard.children.length) this.elements.dashboard.append(this.empty('Keine Treffer gefunden.')); this.renderStats(visibleLinks); }
  favoriteCategory() { return { id: 'favorites', name: 'Favoriten', icon: '★', color: '#facc15', description: 'Schnellzugriff auf markierte Links', collapsed: false, virtual: true, links: this.store.data.categories.flatMap((category) => category.links.map((link) => ({ ...link, sourceCategory: category.id }))).filter((link) => link.favorite) }; }
  renderCategory(category, links) { const section = document.createElement('section'); section.className = `category ${category.collapsed ? 'collapsed' : ''}`; section.style.setProperty('--cat-color', category.color); section.draggable = this.editing && !category.virtual; section.dataset.id = category.id; section.addEventListener('dragstart', () => this.drag = { type: 'category', id: category.id }); section.addEventListener('dragover', (e) => e.preventDefault()); section.addEventListener('drop', () => this.moveCategory(category.id)); const head = document.createElement('div'); head.className = 'category__head'; head.append(this.icon(category.icon, 'category__icon'), this.titleBlock(category.name, category.description, 'h2'), this.categoryActions(category)); const list = document.createElement('div'); list.className = 'links'; links.forEach((link) => list.append(this.renderLink(category, link))); section.append(head, list); return section; }
  renderLink(category, link) { const card = document.createElement('a'); card.className = 'link-card'; card.href = this.safeUrl(link.url) ? link.url : '#'; card.target = link.newTab ? '_blank' : '_self'; card.rel = 'noopener noreferrer'; card.draggable = this.editing && !category.virtual; card.addEventListener('click', (event) => { if (this.editing) event.preventDefault(); else this.trackOpen(link.id); }); card.addEventListener('dragstart', () => this.drag = { type: 'link', id: link.id }); card.addEventListener('dragover', (e) => e.preventDefault()); card.addEventListener('drop', () => this.moveLink(link.id, category.virtual ? link.sourceCategory : category.id)); card.append(this.icon(link.icon || '🔗', 'link-card__icon'), this.linkText(link), this.linkActions(link)); return card; }
  icon(text, className) { const span = document.createElement('span'); span.className = className; span.textContent = text || '🔗'; return span; }
  titleBlock(title, description, heading) { const wrap = document.createElement('div'); wrap.className = 'category__title'; const h = document.createElement(heading); h.textContent = title; const p = document.createElement('p'); p.className = 'muted'; p.textContent = description || ''; wrap.append(h, p); return wrap; }
  linkText(link) { const wrap = document.createElement('div'); const title = document.createElement('h3'); title.textContent = link.title; const desc = document.createElement('p'); desc.textContent = link.description || link.url; const tags = document.createElement('div'); tags.className = 'tags'; (link.tags || []).forEach((tag) => { const chip = document.createElement('span'); chip.className = 'tag'; chip.textContent = tag; tags.append(chip); }); wrap.append(title, desc, tags); return wrap; }
  categoryActions(category) { const wrap = document.createElement('div'); wrap.className = 'edit-tools'; if (!category.virtual) [['＋', () => this.openLinkDialog(category.id)], ['✎', () => this.openCategoryDialog(category)], ['⌄', () => { category.collapsed = !category.collapsed; this.store.save(); this.render(); }], ['🗑', () => this.removeCategory(category.id)]].forEach(([label, fn]) => wrap.append(this.small(label, fn))); return wrap; }
  linkActions(link) { const wrap = document.createElement('div'); wrap.className = 'edit-tools'; [['★', () => this.toggleFavorite(link.id)], ['⧉', () => this.duplicateLink(link.id)], ['✎', () => this.openLinkDialog(null, link)], ['🗑', () => this.removeLink(link.id)]].forEach(([label, fn]) => wrap.append(this.small(label, fn))); const arrow = document.createElement('span'); arrow.className = 'open-indicator'; arrow.textContent = '↗'; const box = document.createElement('div'); box.append(wrap, arrow); return box; }
  small(label, fn) { const button = document.createElement('button'); button.type = 'button'; button.className = 'mini'; button.textContent = label; button.addEventListener('click', (e) => { e.preventDefault(); e.stopPropagation(); fn(); }); return button; }
  empty(message) { const div = document.createElement('div'); div.className = 'empty'; div.textContent = message; return div; }
  renderStats(visible) { const totalLinks = this.store.data.categories.reduce((sum, c) => sum + c.links.length, 0); const favs = this.store.data.categories.flatMap((c) => c.links).filter((l) => l.favorite).length; this.elements.stats.replaceChildren(...[['Kategorien', this.store.data.categories.length], ['Links', totalLinks], ['Favoriten', favs], ['Sichtbar', visible]].map(([label, value]) => { const box = document.createElement('div'); box.className = 'stat'; const strong = document.createElement('strong'); strong.textContent = value; const span = document.createElement('span'); span.textContent = label; box.append(strong, span); return box; })); }
  renderClock() { const now = new Date(); $('clockTime').textContent = now.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' }); $('clockDate').textContent = now.toLocaleDateString('de-DE', { weekday: 'short', day: '2-digit', month: '2-digit', year: 'numeric' }); }
  openCategoryDialog(category = null) { this.fillDialog('category', category || { id: '', name: '', icon: '🗂', color: '#38bdf8', description: '', tags: [] }); }
  openLinkDialog(categoryId, link = null) { this.fillDialog('link', link || { id: '', categoryId, title: '', url: 'https://', icon: '🔗', color: '#38bdf8', description: '', tags: [] }); }
  fillDialog(type, item) { $('dialogTitle').textContent = type === 'category' ? 'Kategorie bearbeiten' : 'Link bearbeiten'; $('itemType').value = type; $('itemId').value = item.id || ''; $('itemTitle').value = item.name || item.title || ''; $('itemUrl').value = item.url || ''; $('itemUrl').disabled = type === 'category'; $('itemIcon').value = item.icon || ''; $('itemColor').value = item.color || '#38bdf8'; $('itemDescription').value = item.description || ''; $('itemTags').value = (item.tags || []).join(', '); $('formError').textContent = ''; this.pendingCategoryId = item.categoryId; this.elements.dialog.showModal(); }
  saveDialog() { const type = $('itemType').value; const id = $('itemId').value; const title = $('itemTitle').value.trim(); if (!title) return $('formError').textContent = 'Bitte einen Namen eingeben.'; if (type === 'link' && !this.safeUrl($('itemUrl').value.trim())) return $('formError').textContent = 'Bitte eine gültige http(s)- oder file-URL eingeben.'; const payload = { icon: $('itemIcon').value.trim(), color: $('itemColor').value, description: $('itemDescription').value.trim(), tags: $('itemTags').value.split(',').map((t) => t.trim()).filter(Boolean) }; if (type === 'category') this.upsertCategory(id, { ...payload, name: title }); else this.upsertLink(id, { ...payload, title, url: $('itemUrl').value.trim() }); this.elements.dialog.close(); this.store.save(); this.render(); }
  upsertCategory(id, data) { const found = this.store.data.categories.find((c) => c.id === id); if (found) Object.assign(found, data); else this.store.data.categories.push({ id: uid('cat'), order: this.store.data.categories.length + 1, collapsed: false, links: [], ...data }); }
  upsertLink(id, data) { const category = this.store.data.categories.find((c) => c.links.some((l) => l.id === id)) || this.store.data.categories.find((c) => c.id === this.pendingCategoryId) || this.store.data.categories[0]; const found = category.links.find((l) => l.id === id); if (found) Object.assign(found, data); else category.links.push({ id: uid('link'), favorite: false, openCount: 0, lastOpened: null, newTab: true, ...data }); }
  findLink(id) { for (const category of this.store.data.categories) { const link = category.links.find((item) => item.id === id); if (link) return { category, link }; } return {}; }
  toggleFavorite(id) { const { link } = this.findLink(id); if (link) link.favorite = !link.favorite; this.store.save(); this.render(); }
  duplicateLink(id) { const { category, link } = this.findLink(id); if (category && link) category.links.push({ ...structuredClone(link), id: uid('link'), title: `${link.title} Kopie` }); this.store.save(); this.render(); }
  removeLink(id) { const { category } = this.findLink(id); if (category) category.links = category.links.filter((l) => l.id !== id); this.store.save(); this.render(); }
  removeCategory(id) { this.store.data.categories = this.store.data.categories.filter((c) => c.id !== id); this.store.save(); this.render(); }
  moveCategory(targetId) { if (!this.drag || this.drag.type !== 'category' || this.drag.id === targetId) return; const categories = this.store.data.categories; const from = categories.findIndex((c) => c.id === this.drag.id); const to = categories.findIndex((c) => c.id === targetId); categories.splice(to, 0, categories.splice(from, 1)[0]); categories.forEach((c, i) => c.order = i + 1); this.store.save(); this.render(); }
  moveLink(targetId, categoryId) { if (!this.drag || this.drag.type !== 'link' || this.drag.id === targetId) return; const source = this.findLink(this.drag.id); const targetCategory = this.store.data.categories.find((c) => c.id === categoryId); if (!source.category || !targetCategory) return; source.category.links = source.category.links.filter((l) => l.id !== this.drag.id); targetCategory.links.push(source.link); this.store.save(); this.render(); }
  trackOpen(id) { const { link } = this.findLink(id); if (link) { link.openCount = (link.openCount || 0) + 1; link.lastOpened = new Date().toISOString(); this.store.save(false); } }
  openFirstResult() { const first = this.elements.dashboard.querySelector('.link-card'); if (first) first.click(); }
  async importFile(file) { if (!file) return; const text = await file.text(); if (file.name.endsWith('.json')) { this.store.data = this.store.normalize(JSON.parse(text)); } else { const doc = new DOMParser().parseFromString(text, 'text/html'); const links = [...doc.querySelectorAll('a[href]')].map((a) => ({ id: uid('link'), title: a.textContent.trim() || a.href, url: a.href, icon: '🔖', description: 'Importierter Browser-Link', tags: ['import'], favorite: false, openCount: 0, lastOpened: null, color: '#38bdf8', newTab: true })); this.store.data.categories.push({ id: uid('cat'), name: `Import ${new Date().toLocaleDateString('de-DE')}`, icon: '📥', color: '#38bdf8', description: `${links.length} importierte Lesezeichen`, order: this.store.data.categories.length + 1, collapsed: false, links }); } this.store.save(); this.render(); }
}

const store = new Store();
store.load().then(() => new Dashboard(store).init());
